name: Check

on:
    pull_request:
        paths-ignore:
            - "**.md"

jobs:
    check:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v3
              with:
                  go-version-file: go.mod

            - name: Test
              run: make test

            - name: Compile
              run: make build

            - name: Exact smoke test
              run: ./smoke -width 64 -height 64 -seed 1 -benchmark
