name: Build

on:
    workflow_dispatch:

    push:
        branches:
            - main
        paths-ignore:
            - "**.md"

    pull_request:
        branches:
            - "*"
        paths-ignore:
            - "**.md"

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Compile
              run: make setup && make build

            - name: Move compiled binary
              run: |
                  if [ "$RUNNER_OS" == "Windows" ]; then
                      mkdir bin
                      mv smoke.exe bin/smoke.exe
                  else
                      mkdir bin
                      mv smoke bin/smoke
                  fi

            - name: Push
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: ./bin
                  publish_branch: bin
                  full_commit_message: Update Binary ${{ matrix.os }} [ci skip]
