name: Build

on:
    workflow_dispatch:

    push:
        branches:
            - main
        paths-ignore:
            - "**.md"

    pull_request:
        branches:
            - "*"
        paths-ignore:
            - "**.md"

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v3
              with:
                  go-version: ^1.18.0

            - name: Compile
              run: make setup && make build

            - name: Move compiled binary
              shell: bash
              run: |
                  if [ "$RUNNER_OS" == "Windows" ]; then
                      mkdir bin
                      mv smoke.exe bin/smoke-windows.exe
                  elif [ "$RUNNER_OS" == "Linux" ]; then
                      mkdir bin
                      mv smoke bin/smoke-linux
                  else
                      mkdir bin
                      mv smoke bin/smoke-macos
                  fi

            - name: Push
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: ./bin
                  publish_branch: bin
                  commit_message: Build binary (${{ matrix.os }}) [ci skip]
                  keep_files: true
